name: Release Builds

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    name: Generate Release APK
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.event.pull_request.merged }}
        name: Checking out main branch
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ANDROID_GITHUB_TOKEN }}

      - if: ${{ github.event.pull_request.merged }}
        name: Getting GitHub Details
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - if: ${{ github.event.pull_request.merged }}
        name: Granting gradlew permissions
        run: chmod +x gradlew

      - if: ${{ github.event.pull_request.merged }}
        name: Execute changeLog generator script
        run: |
          python ./scripts/generate_change_log.py --from-latest-tag -a
          git config user.name "Github actions CI"
          git config user.email "ci@quiph.com"
          git add CHANGELOG.md
          git commit -m "* [r] Appended CHANGELOG.md"
          git push origin main

      - if: ${{ github.event.pull_request.merged }}
        name: Get release file name
        id: zipbundle
        run: echo "::set-output name=filename::$(basename -s .aab app/build/outputs/bundle/release/*.aab)"

      - if: ${{ github.event.pull_request.merged }}
        name: Convert aab to apk
        id: convert_aab
        uses: mukeshsolanki/bundletool-action@v1.0.0
        with:
          aabFile: ${{ steps.release.outputs.aabfile }}
          base64Keystore: ${{ secrets.BASE64_KEYSTORE }}
          keystorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          keystoreAlias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - if: ${{ github.event.pull_request.merged }}
        name: Zip Files
        uses: papeloto/action-zip@v1
        with:
          files: app/build/outputs/mapping/release/mapping.txt ${{ steps.release.outputs.aabfile }} ${{ steps.convert_aab.outputs.apkPath }}
          dest: ${{ steps.zipbundle.outputs.filename }}.zip

      - if: ${{ github.event.pull_request.merged }}
        name: Get Tag
        id: tag
        run: echo "::set-output name=generated::$(echo ${{ steps.zipbundle.outputs.filename }} | sed "s/QTalk-Release-//")"

      - if: ${{ github.event.pull_request.merged }}
        name: Create a draft release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.zipbundle.outputs.filename }}.zip
          generateReleaseNotes: true
          draft: true
          tag: ${{ steps.tag.outputs.generated }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ github.event.pull_request.merged }}
        name: Sending release build to Slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          path: ${{ steps.zipbundle.outputs.filename }}.zip
          channel: android-builds
          initial_comment: ${{ github.event.pull_request.body }}
        continue-on-error: true

      - if: ${{ github.event.pull_request.merged }}
        name: Deleting certificate credentials
        run: |
          rm supershare.keystore.asc
          rm app/supershare.keystore
          rm keystore.properties.asc
          rm keystore.properties
